### PR TITLE
Add filtering by Zabbix application and configure Graphite `from` parameter

### PR DESCRIPTION
**Pull request by adzyoba-gd**

### CODE REVIEW

**Comment by gsilantyev** [comment]
👍

**Comment by amazon** [comment]
Please be aware that your version doesn't support `{host}` parameter in metric templates, so it is incompatible with version that is currently used by Niagara team. See https://github.com/amazon/graphite-to-zabbix/commit/b8288bb669fa11582545d06d2a48ce6e539285bf for details.

**Comment by adzyoba-gd** [comment]
@amazon Niagara's instance of g2zproxy doesn't use `{host}` parameter in template. See Chef recipe in niagara-ci. Moreover, g2zproxy is installed from upstream version in PyPI, which doesn't have your commit.

Applying patch in this PR is safe for your current configuration. After merging this, we can apply your patches.

**Comment by amazon** [comment]
```
graph02{sergey}~ [1000] $ grep '{host}' /opt/g2zproxy/bin/g2zproxy
        if '{host}' in metric['metric']:
                req = '{host}.{metric}'
```

**Comment by amazon** [comment]
Came to agreement with @adzyoba-gd  to put all changes required to keep compatibility with niagara's version into separate PR, so merging this PR as is

**Pull request merged**
